version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
        - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    depends_on:
      - postgres
    
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        - DB_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    ports:
      - "3000:3000"
    environment:
      - DB_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    depends_on:
      - postgres
      
  websocket:
    build:
      context: .
      dockerfile: docker/Dockerfile.websocket
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: