FROM oven/bun:1

ARG DB_URL
ENV DB_URL=$DB_URL

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./turbo.json ./turbo.json
COPY ./apps/web ./apps/web

RUN bun install
RUN bun run generate:db
RUN bun run build

EXPOSE 3000

CMD ["bun", "run", "start:web"]