name : Continuous Deployment Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          build-args: DB_URL=${{ secrets.DB_URL }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mono-frontend:${{ github.sha }}
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 13.203.161.80
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: | 
            docker stop user_frontend || true
            docker rm user_frontend || true
            docker pull atharvthite05/mono-frontend:${{ github.sha }}
            docker run --name user_frontend -p 3000:3000 -e DB_URL=${{ secrets.DB_URL }} -d atharvthite05/mono-frontend:${{ github.sha }}

